[package]
name = "synthic"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
polygen = { path = "../polygen" }

[dev-dependencies]
polygen-csharp = { path = "../polygen/generators/polygen-csharp" }
